#!/bin/bash
sudo systemctl start smbd
# Working configuration
# sudo mount -t cifs //MARTYNA/e /mnt/martyna-e/ -o user=skramer,password=skramer,workgroup=WORKGROUP,ip=192.168.0.10
# sudo mount -t cifs //MARTYNA/c /mnt/martyna-c/ -o user=skramer,password=skramer,workgroup=WORKGROUP,ip=192.168.0.10

sudo mount -t cifs //MARTYNA/c /mnt/martyna-c/ -o credentials=/home/skramer/.samba_credentials,workgroup=WORKGROUP,ip=192.168.0.10,noperm
sudo mount -t cifs //MARTYNA/e /mnt/martyna-e/ -o credentials=/home/skramer/.samba_credentials,workgroup=WORKGROUP,ip=192.168.0.10,noperm

# sudo mount -t cifs //MARTYNA/c /mnt/martyna-c cifs defaults,users,credentials=/home/skramer/.samba_credential,workgroup=WORKGROUP,ip=192.168.0.10
# sudo mount -t cifs //MARTYNA/e /mnt/martyna-e cifs defaults,users,credentials=/home/skramer/.samba_credential,workgroup=WORKGROUP,ip=192.168.0.10

# //MARTYNA/c /mnt/martyna-c/ cifs credentials=/home/skramer/.samba_credentials,comment=systemd.automount,uid=skramer,gid=users,defaults,user 0 0
# //MARTYNA/e /mnt/martyna-e/ cifs credentials=/home/skramer/.samba_credentials,comment=systemd.automount,uid=skramer,gid=users,defaults,user 0 0
